### ISSUE TITLE
Plugin disabled because of DiscordSRV?

### ISSUE THREAD

**Issue by KillazWithaZ** [kangarko/Boss#480] opened 2019-11-11 03:54 UTC
**I know this has already been posted but posting again to get the issue more attention.**

10.11 22:47:38 [Server] INFO ______
10.11 22:47:38 [Server] INFO (____ \
10.11 22:47:38 [Server] INFO ____) ) ___ ___ ___
10.11 22:47:38 [Server] INFO | __ ( / _ \ /___)/___)
10.11 22:47:38 [Server] INFO | |__) ) |_| |___ |___ |
10.11 22:47:38 [Server] INFO |______/ \___/(___/(___/
10.11 22:47:39 [Server] INFO Update messages_en.yml. Move 'Update_Available' (was 'A new version of Boss is available.
10.11 22:47:39 [Server] INFO Current version: {current}; New version: {new}
10.11 22:47:39 [Server] INFO URL: https://www.spigotmc.org/resources/{resourceId}/.') to 'Update.Available'
10.11 22:47:39 [Server] INFO !-----------------------------------------------------!
10.11 22:47:39 [Server] INFO Boss could not integrate to DiscordSRV because the plugin is outdated!
10.11 22:47:39 [Server] INFO !-----------------------------------------------------!
10.11 22:47:39 [Server] INFO Boss 3.5.4 encountered a ClassNotFoundException! Please check your error.log and report this issue with the information in that file.
10.11 22:47:39 [Server] INFO java.lang.ClassNotFoundException: github.scarsz.discordsrv.dependencies.jda.core.entities.TextChannel
10.11 22:47:39 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
10.11 22:47:39 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:156)
10.11 22:47:39 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104)
10.11 22:47:39 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
10.11 22:47:39 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
10.11 22:47:39 [Server] INFO at java.lang.Class.forName0(Native Method)
10.11 22:47:39 [Server] INFO at java.lang.Class.forName(Class.java:264)
10.11 22:47:39 [Server] INFO at org.mineacademy.boss.lib.fo.model.CoM3.const(SourceFile:195)
10.11 22:47:39 [Server] INFO at org.mineacademy.boss.double. .lPT6.onEnable(SourceFile:264)
10.11 22:47:39 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
10.11 22:47:39 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
10.11 22:47:39 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
10.11 22:47:39 [Server] INFO at java.lang.Thread.run(Thread.java:748)
10.11 22:47:39 [Server] INFO _ _ _
10.11 22:47:39 [Server] INFO | | | | ___ ___ _ __ ___| |
10.11 22:47:39 [Server] INFO | |_| |/ _ \ / _ \| '_ \/ __| |
10.11 22:47:39 [Server] INFO | _ | (_) | (_) | |_) \__ \_|
10.11 22:47:39 [Server] INFO |_| |_|\___/ \___/| .__/|___(_)
10.11 22:47:39 [Server] INFO |_|
10.11 22:47:39 [Server] INFO !-----------------------------------------------------!
10.11 22:47:39 [Server] INFO Error loading Boss v3.5.4, plugin is disabled!
10.11 22:47:39 [Server] INFO Running on 1.12.2-R0.1-SNAPSHOT (v1_12_R1) & Java 1.8.0_222
10.11 22:47:39 [Server] INFO !-----------------------------------------------------!
10.11 22:47:39 [Server] INFO Error: github.scarsz.discordsrv.dependencies.jda.core.entities.TextChannel
10.11 22:47:39 [Server] INFO !-----------------------------------------------------!
10.11 22:47:39 [Server] INFO [Boss] Disabling Boss v3.5.4

**Comment by eugene12pvp** [comment] 2019-11-12 01:21
same issue

**Comment by BobbyMere** [comment] 2019-11-12 05:05
same

**Comment by kangarko** [comment] 2019-11-12 08:56
Duplicate of https://github.com/kangarko/Boss/issues/479

**Closed by kangarko** 2019-11-12 08:56 UTC
