### ISSUE TITLE
Unable to use any button in /boss menu since 1.6.7

### ISSUE THREAD

**Issue by SlayG-TR** [kangarko/Boss#90] opened 2018-04-14 12:13 UTC
No button in the GUI makes any sort of response when clicked. Only began after updating to 1.6.7

**Comment by kangarko** [comment] 2018-04-17 17:59
Sorry I cannot reproduce this problem. Make sure you shut your server down and did not use any PlugMan or reloader when updating.

Please also check the console for errors, both on startup and when the menu is opened and clicked.

What's your MC version?

**Comment by kangarko** [comment] 2018-04-29 19:08
Closing due to no answer, comment below if you still have the issue.

**Closed by kangarko** 2018-04-29 19:08 UTC
Labels: Issue: cannot reproduce, Issue: complaint
