### ISSUE TITLE
1.16.1: Equipment Disappearing, and Stats Resetting to 50

### ISSUE THREAD

**Issue by SkooBeep** [kangarko/Boss#620] opened 2020-09-12 05:52 UTC
Hi, so I was trying to add some custom enemies in, but when I setup the armor in the equipment tab exited, and looked in the equipment tab again, it was empty. Also if i set the hp to anything besides 50 it resets to 50. Randomly a pre-existing mob also reset to 50 hp, and the armor disappeared as well. Nothing has been changed in config since it was working.

**Comment by kangarko** [comment] 2020-09-15 17:52
![NkL9bM1g03](https://user-images.githubusercontent.com/1918426/93246297-e0f73180-f78c-11ea-8a75-f399bb4f5dcd.gif)

Sorry I cannot reproduce, I believe this will get fixed on the version coming up tonight, if not please comment below with steps to reproduce.

**Closed by kangarko** 2020-09-15 17:52 UTC
Labels: issue
