### ISSUE TITLE
1.16.2: Boss names not showing

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/Boss#600] opened 2020-08-26 18:44 UTC
Started in 1.15, actually, but bosses very often will not display a name tag so you don't have any idea you're up a super power rabbit until they start attacking you.

Don't know if they should or not, but the "reinforcements" - if those are also pre-designed boss mobs - also do not get names that display.  They DO - however - get SOME - sort of naming data that makes it impossible to name these creatures with a nametag.  I have  polar bear boss that spawns in wolves for reinforcements... it never occurred to me that a person would try this but players have attempted to tame these creatures and give them names after, and found that it just eats their name tag but the name is not applied - suggesting that these mobs do have some kind of name set to them but it's just not visible.

Boss 3.8.5

**Comment by Lariesse** [comment] 2020-08-27 11:46
I was going to report this but you already did it, the same thing happens to me in 1.16.1

https://imgur.com/a/EqriO7r

**Comment by kangarko** [comment] 2020-08-28 13:24
Just to clarify, the "name tag" you mean the name above the boss?

Just tested with the Enderman, and it shows up correctly:
![a](https://i.imgur.com/61vM4u7.png)

Or are you talking about the health action bar message?
![a](https://i.imgur.com/hyiG1GH.png)

**Comment by mrcoffee1026** [comment] 2020-08-28 13:26
Yes, the name above the boss.  While you see them in your pictures above... I have not seen one on a naturally spawned boss in a very long time.

**Comment by kangarko** [comment] 2020-08-28 13:31
Very weird, the Timed_Spawning option for me spawns bosses with their nametags normally: https://i.imgur.com/YFGLBFo.gif

Please ZIP me your full Boss/ folder.

**Comment by mrcoffee1026** [comment] 2020-08-28 13:33
[Boss.zip](https://github.com/kangarko/Boss/files/5142317/Boss.zip)

**Comment by Lariesse** [comment] 2020-08-28 13:34
Name tag doesn't work for me, it just doesn't show up

**Comment by Lariesse** [comment] 2020-08-28 13:37
The health action bar also appears with the name of the entity and not the custom name

**Comment by kangarko** [comment] 2020-08-28 13:38
Interesting, tested your Angry Chicken mob coffee, still cannot reproduce: https://i.imgur.com/gNSuCUO.png

Can you guys try using a test server with just Boss and no other plugins? Just to be sure there is no inteference.

**Comment by Lariesse** [comment] 2020-08-28 13:53
I tested on the test server with only Boss installed and the names now work correctly, how weird

**Comment by Lariesse** [comment] 2020-08-28 14:13
After several tests, I realized that the cause of the error is the StackMob plugin ([click here to go to the plugin link](https://www.spigotmc.org/resources/stackmob-enhance-your-servers-performance-without-the-sacrifice.29999/))

You can reproduce this by installing Boss and StackMob and then spawn a boss, then you will notice that the boss name is broken, but if you add the world you are in in the StackMob world blacklist so that the mobs do not stack, the boss name will be fixed and displayed correctly

**Comment by mrcoffee1026** [comment] 2020-08-28 14:18
hrm good to know... gonna need some kind of workaround that isn't effectively disabling StackMob though.  I'll bug them about it, but there's probably a way to just get it to not attempt to stack bosses... which it won't do anyway since there would never be a condition where there'd be 9+ identical bosses in the required proximity.

**Comment by Lariesse** [comment] 2020-08-28 14:23
In my case it doesn't affect me much, since my bosses are in different worlds so I can put the worlds in the blacklist, but for people who have bosses in a survival world it will be really bad

**Comment by AngellitoX** [comment] 2020-09-01 02:22
Hello there! Have you found a proper fix to your issue?

As a personal comment, I've heard so many times that stacking mob plugins give more problems to your server than solutions. I've seen Aikar explaining it in this way:

- Your server has a spawn-limit of 10 entities. If your stacking mob plugin stacks 10 of those entities, it will now count as 1 and leave the other 9 spots open for new entities to spawn, which at the end is going to cause you lag issues.

Not to mention that most of the stacking mob plugins are sometimes hardcoded and incompatible with many other plugins out there.

I'd deifnitely suggest removing those kind of plugins and instead use Paper's stacking features which will work as expected.

**Comment by Lariesse** [comment] 2020-09-01 10:28
@AngellitoX Sorry to ask, but your comment has very valuable information for me, what are the Paper's stacking features? How can I use it?

**Comment by AngellitoX** [comment] 2020-09-01 17:26
Hello there! 

I just realized I might have understood myself a little bit. Paper won't merge entities such as pigs, zombies etc, for the reasons I stated above, it's counter-productive.

What you can do is stack better those entities that actually cause more lag, such as EXP and items on the ground, please refer to this page and look for `merge-radius` setting on Spigot.yml: https://www.spigotmc.org/threads/guide-server-optimization⚡.283181/

Hope this helps to you all!

**Comment by mrcoffee1026** [comment] 2020-09-01 18:10
I realize that MOST stacking plugins fail to meet their primary goal, the one that I am using actually does mitigate the lag issue, and I've already increased the merge radius setting for spigot.  Paper doesn't include any stacking features that I'm aware of.  The goal of a stacking plugin should not be to stop the spawning of more mobs... just to manage the existing mobs in some useful way.  It's ideal for dealing with the situation created by a player who breeds sheep in a 20x20 pen until there is no longer a way for another entity to physically enter the pen from the crowding.  With stacking, this issue goes away rather quickly.  If it were a spawner creating the mess... six stacks in proximity would still disable the spawner and so would still successfully avert lag disaster.  As for the incidental increase caused by natural spawning which would still technically occur if there weren't enough stacks nearby to count as a maximum of that particular mob... that effect would be rather negligible overall, and those spawns weren't the source of lag in the first place, so they don't matter.

I have contacted the authors of this particular stacking plugin to see if they can remedy the naming issues as I believe it spans further than just the boss mobs by themselves.  I haven't gotten a response yet but do see a couple of pending pull requests to their source which may already deal with the issue, so it may well be remedied shortly anyway.

**Comment by kangarko** [comment] 2020-09-03 17:39
Hi there, glad that we found the problem.

I understand removing the stack plugin will not solve the problem and only open another one.

So the best solution is just to contact the author of that plugin, he can use our simple and free API to get the Boss from an entity then save the name somewhere before stacking and reapply after the stacking has occured:

https://github.com/kangarko/Boss/wiki/Developer-API

**Closed by kangarko** 2020-09-03 17:39 UTC
Labels: issue

**Comment by mrcoffee1026** [comment] 2020-09-20 01:39
Another person had a similar issue to which they replied with "You will need to create your own plugin hook, example https://github.com/Nathat23/StackMob-5/blob/master/src/main/java/uk/antiperson/stackmob/hook/hooks/CitizensHook.java or listen to the StackMergeEvent and cancel it."  Would this be useful in any way?

**Comment by kangarko** [comment] 2020-09-20 08:08
Thanks, added the integration!

**Comment by kangarko** [comment] 2020-09-20 08:13
Does not work as intended, you can try the next version... I have posted on your issue there.

**Comment by mrcoffee1026** [comment] 2020-09-20 13:44
Yeah i thought I made a ticket on this ages ago but I can't find it.  Anyway I didn't actually expect that to work since that event gets called when there is actually a second mob for stacking, and that just isn't the case here.  Bosses have no name from the moment they spawn, there hasn't been time for a second nearby stack of bosses to merge with it, nevermind that with my settings as they are spawning should be rare enough there would never be enough of like-bosses in a near enough radius to stack anyway.  This may still have worked if this event got called every time stackmob messes with a mob, but I think this proves it doesn't, and does show that stackmob is subtly altering every single mob on the server whether it stacks it or not.

**Comment by mrcoffee1026** [comment] 2020-09-21 01:36
Verified with new version - no surprise - that the names still get wiped on bosses.  I didn't think it was from them actually being stacked since there's never more than one of them anywhere, really.  But this is a nice *just in case* measure for possible piles of bosses if spawning gets out of control, we'll certainly need to kill each one, lol.

**Comment by kangarko** [comment] 2020-09-24 17:44
Got it, unfortunately nothing we can do as their API limits that. They would have to change things on their end.

**Comment by Nathat23** [comment] 2020-10-18 09:14
I've added a new event, StackSpawnEvent which should solve your issues. https://github.com/Nathat23/StackMob-5/blob/master/src/main/java/uk/antiperson/stackmob/events/StackSpawnEvent.java

**Comment by mrcoffee1026** [comment] 2020-10-19 14:19
No effect on issue, paper-240,   StackMob 5.3.6
