### ISSUE TITLE
Region blacklist not working with world settings?

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/Boss#100] opened 2018-05-01 02:15 UTC
I've been suspecting something has been up for awhile but thought maybe some things just work "better" now so adjusted numbers in the places where I could... I have 5 bosses set up, limits are here:
```
Limits:
  Global:
    Chunk: 1
    World: 10
  Individual:
    Enabled: false
    Chunk: 1
    World: 10

```

I set each boss to be allowed to spawn in the world World only at 1%, and specified to use the region blacklist as well, and selected every worldguard region available.  My hope was that this would allow 1% world spawning in every place not within a region.  This was the only thing that made sense to me since the other region settings that could be specified were an upward numermic limit (I think default of like 1000) and this setting disappears if the blacklist is used... so I had believed that the percentage set for the world would be applied.  This does not seem to be the case?  There are more bosses now than there have ever been.  People are getting extremely frequent visits from each and every boss... to a point that I think the crazy max region limit is what is being applied... only to the entire world instead of any particular region.  The only thing that seems to be holding them back is the crazy low global limit I've set.  The original settings for this plugin didn't result in near as many spawns and the limits were set much, MUCH higher, which make be believe it was either bugged then or it is now.  Can you enlighten me if the region blacklist + world spawn settings do not operate the way I believe they do, and if I want these to be quite a bit less common than typical mob spawning, how would I go about accomplishing that?  (I can't, for instance, set the spawn rate to less than 1% in a chosen world so... what do I do?)

**Comment by kangarko** [comment] 2018-05-05 10:43
Hello,

so you are saying that the blacklist function works as intended (i.e. it does not spawn inside WG regions but only outside of them), but after applying it the overall Boss ratio has increased and ignores your Global Limits?

**Files**
I am interested (again) in your settings.yml and the specific Boss that behaves as described. Please upload them to pastebin.com and post them :)

Perhaps you can disable Natural Spawning (ie.e Converting) and extend the delay of Timed Spawning? When I tested with Timed Spawning on 5 seconds with 1% spawn chance, yes, Bosses were spawned like crazy, so I increased it to 1 hour to further lower the chances this way.

**Debug 1**
You can also see how many Bosses each world contain with /b f {bossName} to verify that.

**Debug 2**
Finally I suggest you setting Debug to [spawning] for a tiny bit. This will spam console much but it will tell you about when a Boss is attempted to spawn, so you will know what conditions and limits apply and whether the attempt was successful and why. Don't leave the server unattended as this really spams your console.

**Comment by mrcoffee1026** [comment] 2018-05-06 20:25
I've slowed down timed spawning to 600 seconds and I've already had "converting" disabled for awhile to try to ease up on the rates.  the "/boss find *" I've found does not always work very well.  Sometimes it finds the boss standing right by you, sometimes it doesn't find any even when 5 players are battling them.  I find it's less likely to find a boss if players have left that area... and that I am unable to find bosses I am very far away from especially if I've just reentered the world/logged back in to the server, so I can't depend on that for an accurate count.  I have noticed the actual boss count seems to keep fairly "close" to the global limit but I never used to have to set that sow low.  I'm at like 5 for the world now.  Does it automatically follow that I'll perpetually have 5 at all times?  I believe the original default was like 20 or something and we never got anywhere near that many with world spawn set at like 1%... I'd have to keep nudging it up to get any to appear, they didn't really until it was closer to 3%, my spawn rate was less delayed and so on... since you've introduced the blacklist it's like... there's instantly five of them and that count is fairly well maintained.  I mean that's alright if that's what this is supposed to do, it just used to be I had to keep poking at the plugin to see or hear of any bosses, now they're all over (and in droves if I'm not SUPER cautious about settings).  The setting that concerned me when flipping to blacklist mode was... when it is in NOT blacklist mode you can set a region, and those regions get a "count" for a limit, and I believe that default was something like 9,999... but when you switch to blacklist, there's no longer a place to set the count so... does it fall back to that number to apply to every region not in the blacklist?  If so that might explain why it's in a super hurry to catch up on spawning instantly wherever a player might be.  Anyway I'm only guessing right now, they just didn't used to seem this obtrusive initially.   These are the settings I'm using right now:
https://pastebin.com/uG2DFqjF

This isn't horrible right now, though I may lower global to even three at this point.  But it went from like almost never hearing of players running into them to them basically griping about how many there were.  Struggling to find that real happy medium where they sorta spawn in a seemingly natural manner but don't overwhelm anyone.

**Comment by kangarko** [comment] 2018-05-09 13:12
I see, thanks for explanation.

The /b find command finds all loaded entities, so when a chunk is not loaded it is skipped. That's out of my control, but I have edited the error tolerance so if anything happens you will notice in the console right away ("Failed to find Bosses in world ..."). 

Yes, if the blacklist is enabled the only limits that apply are Global and the Individual ones. Same goes for when the blacklist is disabled, however with the extra limiting of maximum amount of Bosses per each region.

Please also post me your Boss' yml file, and try to narrow down the issue to a very specific point so I can have a place to start another testing to save us time.

The Global and Individual limits won't keep your Bosses at their maximum count, they will only prevent the spawn of more Bosses if the maximum amount is already present in the world or chunk.

**Comment by mrcoffee1026** [comment] 2018-05-09 19:43
Well  CURRENTLY it seems the global/chunk limits are being kept at their maximum amounts, but it may just "seem" that way.  As you say the counts aren't actually tested unless the chunks are loaded.  I would have to assume this also applies to functions such as "kill bosses" in the menu... that it wouldn't be able to kill bosses that it hasn't found/loaded the chunks for.  So I could "kill all" the bosses... then have a bunch of people log in... only to find there's a number found that far exceeds the global limit as none of those (which had spawned when other chunks were loaded with players in them before the global limit had been reduced) were found or killed yet.  And when I was having lag/error problems I disabled the plugin entirely for a time... and ran into several bosses even then.  The entities would still exist in their named high heart value states even without the plugin, although I imagine my custom drops wouldn't apply if they were killed, and probably none of their "skills".

The way the blacklist works does seem to explain a bit... does setting just any value for World spawn rates do anything at all?  I assume it does since we've not been running into bosses in creative worlds... yet.  I don't really want them spawning outside of the main world, I have all worlds set to 0% except for "World" which I set to 1%... but from what you said it wouldn't matter if I put this value at 100%, spawn rate would be the same with blacklist enabled.  I just need to verify that setting it to 0% still does something.  

Here's files, I just picked one of the bosses to send I don't have a "boss.yml".  These are all .yml i had to rename them to txt for github to take them.  This may not be that helpful since the way the plugin counts might explain why there seem to be so many.  It may just take time to re-find them all for anyone or for players to return to the chunks where some had spawned previously.
[spigot.txt](https://github.com/kangarko/Boss/files/1989248/spigot.txt)
[bukkit.txt](https://github.com/kangarko/Boss/files/1989250/bukkit.txt)
[PurplePeopleEater.txt](https://github.com/kangarko/Boss/files/1989253/PurplePeopleEater.txt)

**Comment by kangarko** [comment] 2018-05-10 11:29
Hello,

okay here is an explanation, I just wrote an article about it: https://github.com/kangarko/Boss/wiki/Spawning-Limits#but-wait-sometimes-there-are-more-bosses-then-my-limits

The same apply for the /boss butcher command. See, the plugin Winter has offline-scanning functionality but it freezes the servers until finished and kicks all players. At present I see no easy solution for making the limits count Bosses in unloaded chunks on your disk.

If you uninstall Boss, your Bosses will remain and can be removed by for example "/killall named" (beware, this removes all named entities except for players) from Essentials.

**Setting spawn rate for a world to 0 will prevent any Bosses spawning there by Converting or Timed Spawning**. You can still spawn them by command or Spawner Egg.

**Comment by kangarko** [comment] 2018-05-10 11:30
Thanks, I haven't seen anything in particular in the files. Sidenote: Timed Spawning will ignore the spawning range in spigot.yml, but if you have an anti-lag plugin or similar, it may be affected.

**Comment by kangarko** [comment] 2018-05-10 11:35
Actually, I just edited the line to

![a](https://i.imgur.com/vmyexJB.png)

that should turn off region limits completely when blacklist is enabled to prevent confusion and malfunction when you have them on (since it doesn't make sense anyway, because when you have enabled blacklist, the only limits that apply are the per-world spawn chances)

**Comment by mrcoffee1026** [comment] 2018-05-10 18:52
Sounds good.  Yeah I think it's just the limitation that the  chunks have to be active for the bosses to be counted and that's probably all I've been running into, there just suddenly seemed to be a whole lot at once and I already had the numbers set a whole lot lower than they used to be.... seems we just have to find and kill the leftover ones off and things should be kind of "normal" after that.  Thanks!

**Comment by kangarko** [comment] 2018-05-16 11:36
You are welcome! Closing now, should you have any more questions / issues feel free to open a new issue.

**Closed by kangarko** 2018-05-16 11:36 UTC
Labels: Issue: complaint
