### ISSUE TITLE
Timed spawning took over 100ms lag

### ISSUE THREAD

**Issue by ElFlyGod** [kangarko/Boss#274] opened 2019-03-30 19:52 UTC
https://timings.aikar.co/?id=9517d2979d4f472686258a94dea3485c#timings

Had to disable it..

**Comment by kangarko** [comment] 2019-04-02 16:49
Hello,

First, please upload me your ZIP file of Boss. You have something set to 200 ticks and I need to know what is that. Also please check our wikipedia for common troubleshooting when having performance issues.

Lastly, are you sure it's Boss that causes major lag not Essentials? I can see something is hanging a join task in Essentials as well. 

Hope that helps,
Have a wonderful day!

**Comment by ElFlyGod** [comment] 2019-04-03 19:19
https://mega.nz/#!Li4wAYgQ!BadNhTKwnIc2ykQclU1cv1iqX53wdlI6GRejcppr4mM (boss folder)

**Comment by kangarko** [comment] 2019-04-05 16:17
That file is incomplete, I also need to see your settings and potential logs or error files. Upload the entire folder and simply remove MySQL if you use it.

**Comment by KyroOW** [comment] 2019-04-12 14:14
I'm also getting lag when mobs are spawning.
https://timings.aikar.co/?id=7c5950568a044ee887caeedefe31fb0e

**Comment by ElFlyGod** [comment] 2019-04-13 21:04
[Boss 2.2.2] Timed Spawn took 130 ms

Console keeps saying that for every single boss spawn

**Comment by ElFlyGod** [comment] 2019-04-13 21:05
thats my whole boss folder theres nothing else

**Comment by KyroOW** [comment] 2019-04-17 00:52
Still no update on this ? Any performance issues should be top priority, especially on a Premium plugin...

**Comment by kangarko** [comment] 2019-04-17 16:49
@KyroOW I need to you see your entire Boss folder as a ZIP

@ElFlyGod there has to be files like settings.yml and data.db as well, just ZIP me your entire folder

**Comment by ElFlyGod** [comment] 2019-04-17 20:16
https://mega.nz/#!v3QnlKDK!ISuJJSwDQ16K391NjKuUbdIZTk4RZQTSizrQzkgJCFQ

**Comment by kangarko** [comment] 2019-04-19 17:19
@ElFlyGod I went into your error.log file, it says you are using /reload and plugman. These may and will cause more lag over time since we cannot clean the memory properly. #1 priority for you is to test Boss without using these commands.

In settings.yml, your Timed_Spawning is extremely high. Set it to "3 minutes" or more:

![a](https://i.imgur.com/hv8KOCe.png)

I see your World spawn chances are on 100%, that is also too high. I recommend you read through this article: https://github.com/kangarko/Boss/wiki/Common-Issues#boss-is-lagging-my-server

**Comment by ElFlyGod** [comment] 2019-04-20 20:36
I used the reload once i dont constantly reload boss.

Anyway, this does not make sense, i understand that yes having the spawn rate high can lag the server, but thats unrelated, what im saying is that, every time a boss spawns it alerts in console that it took a long time to spawn it, i assume that message is there to warn if it took longer then usual.

[Boss 2.2.2] Timed Spawn took 105 ms (this happens every time a boss spawns)

So if its a problem with the actual spawning of each individual boss that cant be solved by just turning the delay down.

Lastly the reason i have my delay low is cause i need the bosses to spawn instantly as players enter the area because we use them for envoy places and otherwise players can just run in, grab the loot and leave without having to fight any bosses.

**Comment by kangarko** [comment] 2019-04-25 17:10
I understand, okay I feel this can be improved or diagnosed within Boss.

There's another option we can test, please set Debug to [spawning, spawning-lag] in settings.yml and restart. Try to catch up the console messages at the time when the boss spawns successfully and there's the warning, and upload them to pastebin.

Note: There will be a lot of messages.

Thanks

**Comment by KyroOW** [comment] 2019-04-27 17:31
Here is my Boss files. http://www.mediafire.com/file/287akzyjgh6is9a/boss.zip/file

The lag spikes were happening as soon as my first mob "elite" started spawning, at that time, i had no other mob created in the plugin.

**Comment by ElFlyGod** [comment] 2019-04-28 19:26
Im sorry but this is completly unacceptable, how is this possible??

http://prntscr.com/ni03g6

Boss is taking 800MS to spawn?? How, it was causing huge drops to 0tps every 10 seconds during a server event, this is absolutely unacceptable and the second time its happend.. Why is this so intensive?!?

Why cant just set precise spawning locations and boss just spawns the mob every x amount of seconds instead of having it do all of this junk and lag out my server.

**Comment by kangarko** [comment] 2019-04-29 16:43
@KyroOW @ElFlyGod you haven't followed my instructions above, please complete them and upload the log messages to pastebin.com

**Comment by ElFlyGod** [comment] 2019-05-04 13:51
@kangarko https://mega.nz/#!Gz5HiS5b!auGxbYKBbwjhEm0FvsGOE-_UTKfAvZq3nd5Rbq2kEKY Debug log

**Comment by ElFlyGod** [comment] 2019-05-05 21:18
yet another server event with multiple people - boss completely lagged out the server.. please fix this issue..

**Comment by ElFlyGod** [comment] 2019-05-05 21:19
heres the timings https://timings.aikar.co/?id=cb6439eeb7e04368a0dce215a20660c6

**Comment by ElFlyGod** [comment] 2019-05-06 09:20
@kangarko Need help ASAP!

**Comment by ElFlyGod** [comment] 2019-05-06 19:09
@kangarko Still need help please..

**Comment by kangarko** [comment] 2019-05-07 16:37
@ElFlyGod please be patient, as per my profile post I was on travel, there are others in the queue as well

I checked the code and it seems we're not seeing the lag's cause since it's outside of these checks. I've added an extra debug section, please update and set Debug to ["spawning-region"] and post me your console messages. You can clear up Debug completely to only have that one section there.

If you see there's lag coming from that set Timed_Spawning.Performance.Check_Regions to false immediately to stop it and I'll fix it in a bigger update whenever I have time.

Thanks

**Comment by ElFlyGod** [comment] 2019-05-09 16:16
doesnt seam like the regions are the issue, region takes 1ms while "times spawning" takes 600ms
https://hastebin.com/ajakojiroz.css

**Comment by ElFlyGod** [comment] 2019-05-09 16:17
also i reset the log file and it didnt put anything there, after i deleted it and tried again it didnt even regenerate so thats just console output @kangarko

**Comment by ElFlyGod** [comment] 2019-05-11 11:45
@kangarko When will it be fixed, boss has been disabled on my server for a week now its essential for things like envoys, without boss people are able to to loot them without fighting..

**Comment by kangarko** [comment] 2019-05-13 15:57
What's your Discord? I apology that this is getting a pain in the butt for both of us. Let's get this fixed over a priority chat.

**Comment by kangarko** [comment] 2019-05-13 16:01
Add me kangarko#4233 (anyone reading please keep in mind I don't normally use Discord, please use GitHub, SpigotMC or email to take contant)

**Comment by ElFlyGod** [comment] 2019-05-13 16:03
@kangarko Sent a request

**Comment by kangarko** [comment] 2019-05-21 14:54
Closing due to 8 days inactivity, hit me up on Discord if you still need assistance.

For those of you still experiencing this, use the very latest version and set Debug to [ts-map] in settings.yml. You should then see "Map ->" console message. Post it here please.

**Comment by ElFlyGod** [comment] 2019-05-26 09:57
https://pastebin.com/891FRax3 Here it is @kangarko

**Comment by ElFlyGod** [comment] 2019-05-27 16:51
@ElFlyGod

**Comment by ElFlyGod** [comment] 2019-05-27 16:51
@kangarko

**Comment by kangarko** [comment] 2019-05-29 16:48
Thanks, are you able to find how many entities you have on your world? This should be command like /lag if you have Essentials or similar.

**Comment by ElFlyGod** [comment] 2019-05-29 16:49
http://prntscr.com/nv0pq8

**Comment by ElFlyGod** [comment] 2019-05-30 16:33
@kangarko

**Comment by DXUltimate** [comment] 2019-05-31 12:37
This is strangely enough happening to me as well and I have attempted fixes listed above. I can provide the logs if necessary about this, but this normally only happens after the server has been up after sometime (about 4 hours, sometimes less depending oh how resources are handled). Version I am using is 3.2.4.

I cannot provide a timings report because timings returns a 400 error for whatever reason and I'm not sure how to fix that.

@ElFlyGod dude you gotta chill out. He is spending heaps of time fixing these issues. Things take time. Saying stuff like "this is unacceptable" doesn't help matters at all. Things don't magically vanish in a span of 12 hours lol.

**Comment by ElFlyGod** [comment] 2019-05-31 13:35
@DXUltimate You realize i opened this issue more 2 months ago, and i said that a month ago? Even understanding that its completely justified based on how much trouble its caused for me.

**Comment by DXUltimate** [comment] 2019-05-31 14:00
I'm talking about commenting this shit.

https://puu.sh/DzMr7/6c9c25043f.png
https://puu.sh/DzMuz/c88771db79.png
https://puu.sh/DzMuN/ac11055761.png

Every single message put here literally sends him a notification, as well as an email if enabled, so you don't need to constantly send him stuff through here. He's working on it. If it's really causing such a "big issue", just stop using it for now until a fix is provided, instead of complaining/over-dramatizing and tagging him every 12-24 hours, like an inconsiderate bigot.

If you could only comprehend the amount of work, and hours put into this project, I'm sure you would change your views and cease your bickering that you've done here.

**Comment by ElFlyGod** [comment] 2019-05-31 15:51
I have had it disabled since the release of my server, its been out for 2 months now, the mobs are supposed to be spawned at envoy locations to give players a challenge when they try to loot them but now its just "envoy started, lets go there for free loot".

Along with that i was using boss to create dungeons for players to try to fight but now that's been completely disabled for two months as well.

Obviously i'm extremely frustrated when a product I've Paid for isn't working like its supposed to and causing me major issues, getting constant messages and questions from annoyed players asking "Why are there no mobs" and "Why isn't there something to prevent people from looting the envoys instantly"

I've done all i could to help the author solve the issues, I have provided him configs, screenshots, timings, and everything else he asked for yet its been months and the issue has not been resolved. I haven't doubted a single time of how much work he puts into plugins he creates, stop trying to put words in my month that make him the victim.

I have not been dramatic this entire conversation, i'm only saying facts, boss does lag my server and i've tried everything in my power to get the author to solve it.

I have no problem with him taking his time but i do have a problem when you get in here with your bs and try to tell me what i should and shouldn't do being flat our rude and disrespectful.

**Comment by kangarko** [comment] 2019-06-01 11:30
Hi there,

I understand the problem is taking longer, it is due to the fact that we invented own way to mark if the entity is a boss. ElFly posted a log that showed that it is the limit-world section that is slowing things down, that is due to we have to scan through every single living entity on your world and check if it has our special tag.

With thousands of entities, this takes time and there is no easy way to fix.

To your discussion, I agree with DX.  I am selling those items at about $10. Obviously even if I sold 100x of them I still need a day job. Expecting a world-class support when I come home from my main job is rather naive. When I see impolite attitude I generally reply slower after I handle the other tickets, which we have quite a lot.

Having said that, I added a simple cache that should store an entity and its boss name. Not having such a large test scenario right now, but I encourage both of you to give it a shot and set Debug to [ts-map] in settings.yml and reply with the "Map ->" console message. 

Thanks

**Comment by ElFlyGod** [comment] 2019-06-01 17:15
Why is there no option to just toggle off the limit

**Comment by kangarko** [comment] 2019-06-03 05:34
I can, if you are comfortable with your world flooding of Bosses after some weeks/months.

Seems like the lag is from Spigot. Just getting all entities in your world takes 80% of the lag timings.

![a](https://i.imgur.com/622YF0R.png)

I opened a ticket on PaperSpigot: https://github.com/PaperMC/Paper/issues/2125

**Comment by ElFlyGod** [comment] 2019-06-03 05:36
I have them spawning in regions only so i don't mind, please add the option

**Comment by kangarko** [comment] 2019-06-03 06:00
Added

**Comment by kangarko** [comment] 2019-06-04 04:30
Closing – config options were added & cache was added (30% performance gain) and also opened a ticket on PaperSpigot.

**Closed by kangarko** 2019-06-04 04:30 UTC
Labels: Issue: complaint

**Comment by ElFlyGod** [comment] 2019-08-29 15:52
Decided to give the plugin another shot, months later issue still exist, even with the options mentioned above are enabled!

[08:51:05 INFO]: Run -> 582x Entities -> [world=2016, world_nether=40, world_the_end=0, work=0, building=0] Timings (ms) -> {blacklist=0, limit-chunk=0, limit-world=0, world=2, biome=3, conditions=3, limit-region=47}
[08:51:05 INFO]: [Boss 3.4.15] Timed Spawn took 104.85 ms
