### ISSUE TITLE
Boss spawning too many bosses per region

### ISSUE THREAD

**Issue by Vehzx** [kangarko/Boss#374] opened 2019-07-19 09:24 UTC
Hi, having an issue where slime boss is spawning too many bosses in the region, I made a boss region, and a worldguard region, the worldguard region is around an arena that floats in the sky. The boss region is the exact same region as the worldguard region, when the boss spawns, it spawns as 1, which is correct as I have the limit set to 1 in both the worldguard region and boss region. Once I kill the boss, it respawns 3-4 of the boss in the region, I have no idea why it's doing this, when turning debug ["spawning"] on, I get this in my console:

https://pastebin.com/xSBW961e

Also, my timed spawning is set to 1800 seconds.. So I have no clue why this is happening.

**Comment by kangarko** [comment] 2019-07-19 16:20
May I see your entire Boss folder as a ZIP?

**Comment by Vehzx** [comment] 2019-07-21 10:16
Yeah here you go, sorry about the late reply, haven't been able to be at my computer these past couple days

https://drive.google.com/open?id=1mNWnt6I_xA-dYPtEpqzyTD-odzdKPIJV

**Comment by Vehzx** [comment] 2019-07-21 19:55
So, doesn't seem the slime spawns babies toggle under the specific settings works, I disabled baby spawning yet it still splits into smaller slimes when killed.

Also, started getting this message on startup now:

message on startup: https://pastebin.com/0LLPxpeP
my error.log file: https://pastebin.com/8BCB5Rjr

**Comment by Vehzx** [comment] 2019-07-21 21:07
Ok so another update, started using a different mob as the boss, and removed the boss region, only using a worldguard region to spawn the mob inside of, this has it's limitations, for example a boxed in arena thats fully claimed, sometimes allows the mob to spawn outside the arena, or on top of the arena, since the region itself over extends the walls, I fixed this with multiple regions and allowing it to spawn in just one, but made sure that one arena is the entire playable / moveable area, so the mob doesn't walk outside of that area and triggers a timed spawn.

It seems to be working now, although another issue is the on death and on spawn commands just seem to straight up not work. I tried all sorts of commands, although I just want it to broadcast something, but did other commands such as /money give player etc for testing, but no luck, no command works

**Comment by kangarko** [comment] 2019-07-22 06:11
Hey, thanks for your patience. I solved the error message, next time you spawn a new Boss the commands and region spawning should work as a result. 

If you experience any more command issues I added "death-commands" option to Debug, so just set Debug to [death-commands] and restart and post me the console output when that happens.

**Comment by Vehzx** [comment] 2019-07-22 12:15
Will check this out later today and get back to you, thanks

**Comment by Vehzx** [comment] 2019-07-22 16:02
Death commands and spawning commands still not working, but it seems the multiple bosses spawning in one region has been fixed.

Error message I get in console: https://pastebin.com/H4pqsXhy
That error message gets pasted in console when the boss spawns

When the boss spawns, I also get this just above the error message
[18:00:49 INFO]: [death-commands] Running command for boss WildRavager. Commands: [msa announce spawnravager]
[18:00:49 INFO]: [death-commands] Running msa announce spawnravager as console

But in-game nothing  happens, when I use /msa announce spawnravager in-game or through console myself, it works fine and does the command.

**Comment by kangarko** [comment] 2019-07-24 09:11
I apology, the error was caused by the Foundation library marking checking for null when we allow it, I have solved that.

I am now closing this since I believe the next version will resolve the problem. If you will have any more questions just write below.

**Comment by Vehzx** [comment] 2019-07-24 19:49
Hi, it seems the spawning commands are now working fine, I tried multiple commands and they all worked.

Death commands however still are not being triggered, and i'm not sure why, I tried many different commands for this too, but still nothing.

Even with "death-commands" set to in debug, I get nothing appear in my console when I kill the boss.

**When spawning the boss I get the following:**
>.... [21:36:00 INFO]: [death-commands] Running command for boss WildRavager. Commands: [msa announce spawnravager]
>.... [21:36:00 INFO]: [death-commands] Running msa announce spawnravager as console
>.... [21:36:00 INFO]: Announcement spawnravager sent to all players

Once killing the boss, nothing else appears.

It also seems that item drops are not dropping, I am using the default option that disables the vanilla drops, yet when killing my ravager boss, it drops saddles (which im pretty sure are a vanilla drop).
For testing purposes, I put an acacia sapling in the drops for my boss, and set it to 100%, but it doesn't drop. I will leave a link for my current boss folder, as some things changed around since the first one I gave you.

My boss folder: https://drive.google.com/file/d/1mNWnt6I_xA-dYPtEpqzyTD-odzdKPIJV/view?usp=sharing

**Comment by kangarko** [comment] 2019-07-27 12:35
Are you sure you're running on the latest version? Just tested without problems:

![a](https://i.imgur.com/G3Wina6.png)

I did get the acacia drop into my inventory through. Seems like there may be some undiscovered problem, please attach me your full console log from the server start till it says Done as well as the console log when you spawn/kill the boss.

**Comment by Vehzx** [comment] 2019-07-27 17:38
I'm not home currently, once I'm home I will make sure I'm updated to latest version, test and if still nothing I will paste my entire startup log.

**Comment by Vehzx** [comment] 2019-07-27 22:33
Hi, I made sure i'm updated to the latest version of boss. Killing the boss still does not trigger death commands, and the acacia sapling doesn't drop, I get a saddle everytime the boss is killed (again I think this is a vanilla drop).

Here is my entire console startup log: https://pastebin.com/GJU32KaC

At the very end of the log, you see where I spawned the boss 2 times, I spawned it once, killed it, then spawned another and killed it again, just to be sure.

**Comment by kangarko** [comment] 2019-07-30 16:42
Hmm that's really odd. Seems like the entire entity death event is not fired properly for you. Can you enable Lightning on Death for the Boss to see if the event is being fired at all for your Boss?

Are you running any other plugin potentially modifying what happens on death? If so please test with that plugin disabled.

**Comment by Vehzx** [comment] 2019-07-30 18:13
Lighting on death has always been enabled for the boss, and as far as i'm aware I have no plugin that modifies what happens on death (I have MC-Cron which sends commands at a certain time, but nothing to do with on-death).

The lightning does not strike when I kill the boss either.

I will show a screenshot here of all my plugins, I would say I'd send you the entire folder and let you load it and try testing, but some plugins are premium and have keys. I don't want to be blacklisted from the plugin or something if it thinks i'm sharing my copy etc.

https://i.gyazo.com/53ea9d35435e137205865f7f3bbfde93.png

If you need any config files from me to see how I have things setup, i'll gladly send over configuration files of any plugins that you want to see the setup of.

**Comment by kangarko** [comment] 2019-07-31 15:51
Yeah really seems like the event is not fired at all. Would it be possible to temporarily move all plugins except for Boss to a backup folder to see if the event starts to fire? Just for one testing round.

**Comment by kangarko** [comment] 2019-07-31 15:52
Just a check - are you able to right click with a boss egg to open a menu? If Bukkit fails to register listeners it completely ignores the entire class that would also prevent the interact event from being listened to, since it is in the same class as the death event.

**Comment by Vehzx** [comment] 2019-08-01 02:37
Just tried to right click a boss egg to open a menu, when right clicking, no matter where I look it just spawns the boss, I tried shift-right clicking the egg, same thing, I tried aiming in the sky, it just spawns it in the sky and the boss falls to the ground.

Made a backup and just loaded the plugin with only boss, the same thing happens, just the boss spawns when I right click an egg, no matter where I look.

BUT, my spawn-commands and death-commands are working with just boss installed, which means its a plugin, I will try to go through all my plugins, loading them 1 by 1 to figure out what it is causing no death event commands. When I find out I will let you know.

**Comment by Vehzx** [comment] 2019-08-01 02:57
Ok I found out what plugin is causing this.

WildStacker: https://www.spigotmc.org/resources/%E2%AD%90%EF%B8%8F-wildstacker-%E2%AD%90%EF%B8%8F-stack-mobs-items-blocks-spawners-with-hopper-support.60648/

I tried looking through the config to see if there is anyway to fix the issue but it doesn't seem there is anything I can do.

Not sure if you can fix this, or if it's something they need to do. But it is definitely this plugin that causes no death-event commands to be triggered.

Incase you don't know what the plugin does, it stacks mobs together to reduce the amount of entities in chunks, but it doesn't target named-mobs (that's an option you can configure) and I have that enabled. So bosses are not affected by this anyway, but it is definitely the plugin that's causing it.

**Comment by kangarko** [comment] 2019-08-01 15:31
My bad, I meant left click. Right click is indeed meant to spawn the boss. Sorry !

Are you able to use an alternative stacking plugin? For CoreArena we support https://www.spigotmc.org/resources/stackmob-enhance-your-servers-performance.29999/ and people reported it working just fine. I recommend you test it and if it breaks Boss then I will add integration for it as well. Does not seem like there is anything I can do if the event is getting hijacked from us from that plugin.

**Comment by Vehzx** [comment] 2019-08-01 16:16
Will check this out later today and test it, will get back to you if it's working or not.

**Comment by Vehzx** [comment] 2019-08-04 15:33
Seems to work fine with the plugin you recommend, just sucks since WildStacker is premium so bit of a pointless buy on my end, but no worries I can use stackmob, thanks for the help :p

**Comment by kangarko** [comment] 2019-08-09 16:21
You're welcome!

**Closed by kangarko** 2019-08-09 16:21 UTC
Labels: Confirmed
