### ISSUE TITLE
1.8.8: Question & Bugs

### ISSUE THREAD

**Issue by IceGames23** [kangarko/Boss#1240] opened 2024-04-05 06:22 UTC
Hello,

I'm running Boss v4.11.0 right now, but I'm having some issues since 4.10.3, here are they:

1º) "Persistent" bosses transforms in normal mobs after a restart and aren't cleaneble with /boss butcher. I don't know why this occours, but always when I restart my server and I run /boss butcher, a lot of "bosses" transforms in normal mobs. That's really annoying, because always when I restart my server I have to run /difficulty 0 for clean all bosses, and this breaks other plugins and areas that uses mobs.

2º) This is more a question, but maybe a issue too: I'm running my dungeons with "spawn_rule join region", when a player enter in some area the bosses of this area are spawned using . Normally I have 4-10 location mobs per spawn rule. The problem is, a lot of times, when I enter in some region with more then 12+ mob locations (idk exactly) some locations the bosses don't spawn, only spawn some locations, not all of them. Is there some limitation of locations per spawn rule?

3º) This is related with the second issue. A lot of times when I enter in this regions with a lot of locations, the bosses spawns with items that shouldn't spawn, like for Zombie bosses, spawns with shovel or Skeletons spawns with bows. Are not all of them, but a considerable amount. This is related maybe with the second issue?

If you need to send something please let me know, thank you in advance.

**Comment by kangarko** [comment] 2024-04-05 13:50
Please try the next Boss version released in 1h and let me know.

**Comment by kangarko** [comment] 2024-04-06 06:42
I'm gonna investigate asap. Can you please post your /boss debug and let me know which boss is on the image that is bugged?

**Comment by kangarko** [comment] 2024-04-09 16:47
I am looking into your file and looks like you've spent a lot of time making these mobs, so I'll make sure the problem gets resolved.

Do you have any mob/entity stacking plugin? If not, and if possible, drop the old PaperSpigot 1.8.8 instead of PandaSpigot for a day of testing to see if the problem goes away. Because some stack plugins or forks that manipulate entities will remove our nbt tag to help identify bosses.

**Comment by kangarko** [comment] 2024-04-10 13:33
https://www.loom.com/share/a48ec09052574959809b9c3822876f3a

**Comment by kangarko** [comment] 2024-04-11 18:10
Can you please do a test server with just "Boss" installed, please? Just to be 100% sure it's not caused by another plugin. If that won't do then I will inject some more debug messages into Boss to help us nail down the issue.

**Comment by kangarko** [comment] 2024-04-11 18:56
If possible can you zip the entire bugged server to ufile.io, all files, so I can reproduce exactly 100% matching your setup?

**Comment by kangarko** [comment] 2024-04-12 10:44
@IceGames23 I was able to reproduce on your server. After, I reworked metadata storage, and the bug seemed to be gone. Can you please confirm it's fixed on your end too using this dev build? Make sure to remove the old corrupted bosses since they are not able to be fixed.

[Boss-4.11.2.jar.zip](https://github.com/kangarko/Boss/files/14957702/Boss-4.11.2.jar.zip)

**Comment by kangarko** [comment] 2024-04-12 19:03
Thanks for the feedback!

Please test this dev build to see if mobs spawn without equipment. Please note that we remove the equipment after 4 ticks so it will be shown for a very short time after the mob spawned. This has to do with your old MC limitations:

[Boss-4.11.2.jar.zip](https://github.com/kangarko/Boss/files/14962564/Boss-4.11.2.jar.zip)

**Comment by kangarko** [comment] 2024-04-16 18:00
Unfortunately that might be your Spigot fork, we already call the proper APIs. This would be a wontfix issue.

**Closed by kangarko** 2024-04-16 18:00 UTC
Labels: issue
