### ISSUE TITLE
ViaBackwards / Boss Error

### ISSUE THREAD

**Issue by freak-dk** [kangarko/Boss#76] opened 2018-03-26 12:50 UTC
Hi

Not sure where to report his, if this is not something you can do anything about I am sorry.

Basically experiencing the following error,
https://pastebin.com/F2BTsNZS

Paper version git-Paper-1227 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

Log snippet, no Boss errors on load
	Line 17: [14:48:29] [Server thread/INFO]: [Boss] Loading Boss v1.5.8
	Line 209: [14:48:38] [Server thread/INFO]: [Boss] Enabling Boss v1.5.8
	Line 995: [14:49:22] [Craft Scheduler Thread - 21/INFO]: [Boss] Clearing data.db file ..
	Line 3724: [14:50:08] [Server thread/ERROR]: [Boss] Unhandled exception occured in onPacketSending(PacketEvent) for Boss

**Comment by kangarko** [comment] 2018-03-28 19:14
Temporary players? That's odd. Make sure you have latest ProtocolLib.

Please ask the dev of ViaVersion whether this may be the cause before I silence it. I can mute the error but I want to make sure it's the best (only) option.

**Comment by kangarko** [comment] 2018-04-06 12:17
Closing due to no reply. Let me know it it persists.

**Closed by kangarko** 2018-04-06 12:17 UTC
Labels: Issue: complaint
