### ISSUE TITLE
Paper 1.16.5: When boss die to mobs it does not drop loot even after set to 100%

### ISSUE THREAD

**Issue by jahangir6969** [kangarko/Boss#865] opened 2021-04-16 19:13 UTC
Paper 1.16.5 and no error in console

The issue with boss tm plugin at the moment is that items do not drop if an boss is killed by an mob instead of an player. 

Here an video of it in action:
https://youtu.be/aSNxvaBncN0

Here it set to an 100%
https://imgur.com/a/lFHpXHt

here is the plugin I am using at the moment: https://imgur.com/a/gN7afqH

**Comment by IAmOrion15** [comment] 2021-04-20 16:41
First off, (for the creator) thanks for fixing the issue with the mobs not spawning after a restart on the server. But yeah, so far this is the only issue I can find. Items don't retain their % drops after a restart. Thank you for fixing the other issues, hope you can work this one out too soon! :)

**Comment by kangarko** [comment] 2021-04-21 09:48
Please upload your boss yml.

I cannot reproduce this issue, even after a restart the 100% chance is persistent.

**Comment by kangarko** [comment] 2021-04-21 09:48
Also there's gonna be a new version of Boss tonight, try that one please :)

**Comment by IAmOrion15** [comment] 2021-04-21 10:05
> Please upload your boss yml.
> 
> I cannot reproduce this issue, even after a restart the 100% chance is persistent.

Ok so here is what I discovered after going to my boss yml files. If you change and save the drop chances in the file directly, it works. But if you use the GUI is doesn't save. So in other words, this is still an issue, but it isn't the end of the world and isn't EXTREMELY important. Thank you though for your time kangarko, thank you for continuing to fix and update this plugin. If you stuck with it consistently to make it better with like new abilities and other stuff, I guarantee you this plugin would be just as if not more popular than MythicMobs because of the GUI system you have. Once again, thank you! :)

**Comment by kangarko** [comment] 2021-04-21 10:46
Thanks <3

Are you on the latest version by the way? https://github.com/kangarko/Boss/releases/tag/3.10.3 Because I solved a savings issue recently.

**Comment by IAmOrion15** [comment] 2021-04-21 11:23
Unless you just released one, I am using the latest one :). I just tested from last night. Also yeah you did fix a lot of saving issues, I noticed so thank you.

**Comment by kangarko** [comment] 2021-04-21 11:48
Sure, please report when the next version is out tonight! Also set Debug option in settings.yml to "[drops]" and report the console messages when the boss dies and drops malfunction.

**Comment by IAmOrion15** [comment] 2021-04-21 14:37
Alrighty! Also how do you create new skills? If you don’t mind me asking?

**Comment by kangarko** [comment] 2021-04-29 16:09
So sorry for a late reply! At present, the only way to add new skills is through our developer API. We're not planning on adding the ability to create new skills in-game for the moment. Closing this, lemme know if there's anything else I can help you with.

**Closed by kangarko** 2021-04-29 16:09 UTC
Labels: issue
