### ISSUE TITLE
New DiscordSRV update problem

### ISSUE THREAD

**Issue by DumbatorCZ** [kangarko/Boss#479] opened 2019-11-11 02:59 UTC
S verzí DirscordSRV 1.18.0 Boss plugin crashne při načítání.

11.11 03:47:53 [Server] Startup [02:47:53 INFO]: [Boss] Enabling Boss v3.5.4
11.11 03:47:53 [Server] Startup [02:47:53 INFO]: ______
11.11 03:47:53 [Server] Startup [02:47:53 INFO]: (____  \
11.11 03:47:53 [Server] Startup [02:47:53 INFO]:  ____)  ) ___   ___  ___
11.11 03:47:53 [Server] Startup [02:47:53 INFO]: |  __  ( / _ \ /___)/___)
11.11 03:47:53 [Server] Startup [02:47:53 INFO]: | |__)  ) |_| |___ |___ |
11.11 03:47:53 [Server] Startup [02:47:53 INFO]: |______/ \___/(___/(___/
11.11 03:47:53 [Server] Startup [02:47:53 INFO]:   
11.11 03:47:53 [Server] Startup [02:47:53 INFO]: !-----------------------------------------------------!
11.11 03:47:53 [Server] Startup [02:47:53 INFO]: Boss could not integrate to DiscordSRV because the plugin is outdated!
11.11 03:47:53 [Server] Startup [02:47:53 INFO]: !-----------------------------------------------------!
11.11 03:47:53 [Server] Startup [02:47:53 INFO]: Boss 3.5.4 encountered a ClassNotFoundException! Please check your error.log and report this issue with the information in that file.
11.11 03:47:53 [Server] Startup [02:47:53 INFO]: java.lang.ClassNotFoundException: github.scarsz.discordsrv.dependencies.jda.core.entities.TextChannel
11.11 03:47:53 [Server] Startup [02:47:53 INFO]: at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
11.11 03:47:53 [Server] Startup [02:47:53 INFO]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139)
11.11 03:47:53 [Server] Startup [02:47:53 INFO]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85)
11.11 03:47:53 [Server] Startup [02:47:53 INFO]: at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
11.11 03:47:53 [Server] Startup [02:47:53 INFO]: at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
11.11 03:47:53 [Server] Startup [02:47:53 INFO]: at java.lang.Class.forName0(Native Method)
11.11 03:47:53 [Server] Startup [02:47:53 INFO]: at java.lang.Class.forName(Class.java:264)
11.11 03:47:53 [Server] Startup [02:47:53 INFO]: at org.mineacademy.boss.lib.fo.model.CoM3.const(SourceFile:195)
11.11 03:47:53 [Server] Startup [02:47:53 INFO]: at org.mineacademy.boss.double. .lPT6.onEnable(SourceFile:264)
11.11 03:47:53 [Server] Startup [02:47:53 INFO]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
11.11 03:47:53 [Server] Startup [02:47:53 INFO]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
11.11 03:47:53 [Server] Startup [02:47:53 INFO]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
11.11 03:47:53 [Server] Startup [02:47:53 INFO]: at java.lang.Thread.run(Thread.java:748)
11.11 03:47:53 [Server] Startup [02:47:53 INFO]:   _   _                       _
11.11 03:47:53 [Server] Startup [02:47:53 INFO]:   | | | | ___   ___  _ __  ___| |
11.11 03:47:53 [Server] Startup [02:47:53 INFO]:   | |_| |/ _ \ / _ \| '_ \/ __| |
11.11 03:47:53 [Server] Startup [02:47:53 INFO]:   |  _  | (_) | (_) | |_) \__ \_|
11.11 03:47:53 [Server] Startup [02:47:53 INFO]:   |_| |_|\___/ \___/| .__/|___(_)
11.11 03:47:53 [Server] Startup [02:47:53 INFO]:                     |_|
11.11 03:47:53 [Server] Startup [02:47:53 INFO]: !-----------------------------------------------------!
11.11 03:47:53 [Server] Startup [02:47:53 INFO]: Error loading Boss v3.5.4, plugin is disabled!
11.11 03:47:53 [Server] Startup [02:47:53 INFO]: Running on 1.14.4-R0.1-SNAPSHOT (v1_14_R1) & Java 1.8.0_222
11.11 03:47:53 [Server] Startup [02:47:53 INFO]: !-----------------------------------------------------!
11.11 03:47:53 [Server] Startup [02:47:53 INFO]: Error: github.scarsz.discordsrv.dependencies.jda.core.entities.TextChannel
11.11 03:47:53 [Server] Startup [02:47:53 INFO]: !-----------------------------------------------------!
11.11 03:47:53 [Server] Startup [02:47:53 INFO]: [Boss] Disabling Boss v3.5.4

**Comment by KillazWithaZ** [comment] 2019-11-11 03:53
Getting this issue as well. Tried updating both plugins and nothing works. 

I know kangarko has a lot on his plate but this needs to be fixed asap! A big part of my server relies on this plugin and I can't get rid of DiscordSRV.

**Comment by DumbatorCZ** [comment] 2019-11-11 03:59
Older version of DiscordSRV 1.17. works just fine. Use older version, until Kangarko updates class packages, which were changed. :)

**Comment by KillazWithaZ** [comment] 2019-11-11 04:05
> Older version of DiscordSRV 1.17. works just fine. Use older version, until Kangarko updates class packages, which were changed. :)

Thanks my good sir, will give this a shot. 

On a different note, do you know why Boss needs to hook into DiscordSRV? I don't see any correlation between the 2 and it seems arbitrary that it would need to hook into discord?

**Comment by KillazWithaZ** [comment] 2019-11-11 04:06
I can confirm that using an older version of DiscordSRV will fix the problem. Thanks again DumbatorCZ!

**Comment by BobbyMere** [comment] 2019-11-14 00:11
Is problem being worked on? He replied but didn't give an answer to it

**Comment by KillazWithaZ** [comment] 2019-11-14 00:22
If you go into "versions" section on discordsrv and download the last
version before the most recent one, the problem should be fixed.

Kangarko just has to updaye the libraries for discordsrv. I'm assuming
it'll be fixed soon.

Ben

**Comment by BobbyMere** [comment] 2019-11-14 01:28
The older version of discordSRV now conflicts with other plugins.

**Comment by DumbatorCZ** [comment] 2019-11-14 02:29
You mean 1.17? With which plugins you have conflicts?

kangarko: What about opening Boss Discord for community, so people can share their problems/tips and bosses. Like... this is in this time somewhat expected from premium plugins

**Comment by kangarko** [comment] 2019-11-15 19:25
Sorry everyone for waiting, ever since I moved countries I find myself not having time for Spigot. 

I'm building a team with positions open for Java developers (paid), anyone feel free to apply [here](https://www.spigotmc.org/threads/403375/).

**This is now fixed.**

**Closed by kangarko** 2019-11-15 19:25 UTC
