### ISSUE TITLE
Minecraft Version: 1.16.3

### ISSUE THREAD

**Issue by vanderlieklar** [kangarko/Boss#709] opened 2020-11-05 20:35 UTC
I created a bossmonster. a witherskeleton boss that wears netherite armor. But diamond armor has the same issue. As soon as the boss died and dropped the armor he wore, the armor pieces dropped are deleted inside the bosses editor. The next boss I spawn using the same bossegg, is missing these armorpieces. So far I only used the ingame configuration of the plugin.

I'll attach the bosses file for you.

[bosses.zip](https://github.com/kangarko/Boss/files/5497285/bosses.zip)

Thank you in advance,

laerse

**Comment by kangarko** [comment] 2020-11-09 19:09
Sorry for delay, will get this fixed within 1-2 days max

**Comment by kangarko** [comment] 2020-11-10 12:55
Could not reproduce this, made you a small video:

https://www.loom.com/share/43cee83e272e49b8afc6273bb0908ad3?from_recorder=1

Closing, comment below if you test on an empty server without other plugins than Boss and still get this issue

**Closed by kangarko** 2020-11-10 12:55 UTC
Labels: issue
