### ISSUE TITLE
1.17.1: The equipment and HP of bosses are reset, and disabling messages from the actionbar does not work

### ISSUE THREAD

**Issue by NewJeb** [kangarko/Boss#949] opened 2021-11-14 10:33 UTC
1) 1.17.1

2) I cannot understand how this exactly happens, but there is a fact that all bosses lose their equipment, hp and at the same time remain valid and drop drops from them, and also turning off the message about the boss's HP does not work

3) 
![2021-11-14_13 24 57](https://user-images.githubusercontent.com/50917369/141677228-b71913a9-0dac-48e0-8ba5-592c3aaf83a8.png) 
![image](https://user-images.githubusercontent.com/50917369/141677264-d18ed328-3e55-4408-9566-830eb822b594.png)

https://youtu.be/PPpsy-2PxXs

**Comment by kangarko** [comment] 2021-11-16 12:57
Likely a server or a plugin incompatibility. We only support Paper, not third party forks if you use one. Other plugins such as StackMob, MythicMobs etc., or even grief prevention plugin rollbacking entities may cause this. Closing in good faith that this can be solved by finding the problematic plugin, but let me know if there is anything I can help you with!

**Closed by kangarko** 2021-11-16 12:57 UTC
Labels: issue

**Comment by NewJeb** [comment] 2021-11-16 14:04
> Likely a server or a plugin incompatibility. We only support Paper, not third party forks if you use one. Other plugins such as StackMob, MythicMobs etc., or even grief prevention plugin rollbacking entities may cause this. Closing in good faith that this can be solved by finding the problematic plugin, but let me know if there is anything I can help you with!

... What? What makes you think that I do not use paper, but also third-party plugins, I use paper and only your plugin for bosses

**Comment by kangarko** [comment] 2021-11-16 14:18
Thanks for clarifying, sorry for assuming. In the next version, please type /boss debug and upload me your ZIP file from Boss folder so I can have a look - let me know exactly which Boss is having this problem.

**Comment by NewJeb** [comment] 2021-11-16 19:35
> Thanks for clarifying, sorry for assuming. In the next version, please type /boss debug and upload me your ZIP file from Boss folder so I can have a look - let me know exactly which Boss is having this problem.
[debug.zip](https://github.com/kangarko/Boss/files/7549306/debug.zip)
![image](https://user-images.githubusercontent.com/50917369/142053345-b6b2969a-d219-4e5c-9c08-c1e8a086dcfc.png)
![2021-11-16_22 32 07](https://user-images.githubusercontent.com/50917369/142053357-f4356cf4-77e6-4ece-8db2-776a684d0b4b.png)
A funny situation, 7 of them spawned, although the maximum in a day was 5 and the server was turned off!

I attach additionally screenshots and what you asked for, by the way I am using the latest version

**Comment by kangarko** [comment] 2021-11-17 07:30
In settings.yml in Spawning.World_Limit your limit is 300. Your li4.yml Boss, the one on the image, has 1 Boss at 50 blocks distance: https://i.imgur.com/LtVnxyA.png.

You mentioned the limit was 5, but I can see it is one, I am seeing the wrong file?

**Comment by kangarko** [comment] 2021-11-17 07:31
Please also set Debug key in settings.yml to [spawning] and see your console. Our plugin will spam every time it tries to spawn a Boss so it will give you some ideas why the Bosses could have spawned over limit.

**Comment by NewJeb** [comment] 2021-11-17 12:17
> Please also set Debug key in settings.yml to [spawning] and see your console. Our plugin will spam every time it tries to spawn a Boss so it will give you some ideas why the Bosses could have spawned over limit.

Everything is fine with the spawn, the problem is that the boss's meta data is reset
![2021-11-17_15 14 59](https://user-images.githubusercontent.com/50917369/142198945-99904c8f-59b7-4d05-8261-fecfa84e35e2.png)
[debug (1).zip](https://github.com/kangarko/Boss/files/7554524/debug.1.zip)

**Comment by NewJeb** [comment] 2021-11-17 19:26
The limit does not work only on the one that I threw you in the screenshots, in others, all the data gets lost, it seems to me that the problem is in unloading chunks

**Comment by NewJeb** [comment] 2021-11-18 16:55
[19:53:33 WARN]: [Boss] Task #287 for Boss v4.0.8 generated an exception
java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.MinecraftKey.getNamespace()" because "minecraft" is null
        at org.bukkit.craftbukkit.v1_17_R1.util.CraftNamespacedKey.fromMinecraft(CraftNamespacedKey.java:24) ~[patched_1.17.1.jar:git-Airplane-103]
        at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlock.biomeBaseToBiome(CraftBlock.java:348) ~[patched_1.17.1.jar:git-Airplane-103]
        at org.bukkit.craftbukkit.v1_17_R1.CraftRegionAccessor.getBiome(CraftRegionAccessor.java:202) ~[patched_1.17.1.jar:git-Airplane-103]
        at org.mineacademy.boss.lib.remain.Remain.getBiome(Remain.java:1316) ~[Boss-4.0.8.jar:?]
        at org.mineacademy.boss.spawn.SpawnRuleRandom.canRun(SpawnRuleRandom.java:114) ~[Boss-4.0.8.jar:?]
        at org.mineacademy.boss.spawn.SpawnRuleRandomPeriod.canRun(SpawnRuleRandomPeriod.java:77) ~[Boss-4.0.8.jar:?]
        at org.mineacademy.boss.spawn.SpawnRuleRandomPeriod.onTick(SpawnRuleRandomPeriod.java:99) ~[Boss-4.0.8.jar:?]
        at org.mineacademy.boss.spawn.SpawnRule.tick(SpawnRule.java:811) ~[Boss-4.0.8.jar:?]
        at org.mineacademy.boss.task.TaskSpawnRule.run(TaskSpawnRule.java:20) ~[Boss-4.0.8.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Airplane-103]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Airplane-103]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1564) ~[patched_1.17.1.jar:git-Airplane-103]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:492) ~[patched_1.17.1.jar:git-Airplane-103]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1480) ~[patched_1.17.1.jar:git-Airplane-103]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1279) ~[patched_1.17.1.jar:git-Airplane-103]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Airplane-103]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]

> Please also set Debug key in settings.yml to [spawning] and see your console. Our plugin will spam every time it tries to spawn a Boss so it will give you some ideas why the Bosses could have spawned over limit.

**Comment by kangarko** [comment] 2021-11-24 12:02
Please report the null pointer exception to Paper. We could silence it but it looks like a problem on their end. I do not think it unloading chunks is the issue (at least not on a default setup), since we have hundreds of people with large maps and unloading works fine. There can be some modifications you did to the server I am unaware of that cause custom NBT tags to be lost perhaps?

**Comment by NewJeb** [comment] 2021-11-24 18:30
> Please report the null pointer exception to Paper. We could silence it but it looks like a problem on their end. I do not think it unloading chunks is the issue (at least not on a default setup), since we have hundreds of people with large maps and unloading works fine. There can be some modifications you did to the server I am unaware of that cause custom NBT tags to be lost perhaps? So far you're the only one reporting this without using StackMob plugins etc., that makes me think it needs to be a setting in the server then.

Yes, we use custom NBT tags, both in loot and in boss armor

**Comment by kangarko** [comment] 2021-11-24 19:01
I see. Let me know how the bug report goes. I am here to help you with Boss -- I understand you dont want to waste time on endless debugging. I'll let you know when I find something. 

You can try disabling those loots and armor for a test round. 

And most importantly, we added /boss debug command - please upload the ZIP file the command gives you to the reply below.

**Comment by NewJeb** [comment] 2021-11-25 10:13
> I see. Let me know how the bug report goes. I am here to help you with Boss -- I understand you dont want to waste time on endless debugging. I'll let you know when I find something.
> 
> You can try disabling those loots and armor for a test round.
> 
> And most importantly, we added /boss debug command - please upload the ZIP file the command gives you to the reply below.
[debug.zip](https://github.com/kangarko/Boss/files/7602037/debug.zip)

**Comment by kangarko** [comment] 2021-12-01 17:23
Sorry for the delay, I am looking into this in 1-2d.

**Comment by kangarko** [comment] 2021-12-02 15:52
I noticed some plugins like AureliumMobs or Citizens-addons, can you please try removing those plugins for a short test round to see if the problem persists? I was not able to reproduce this bug.

**Comment by NewJeb** [comment] 2021-12-02 16:41
> 

What addons for Citizens are you talking about?

**Comment by NewJeb** [comment] 2021-12-02 16:41
> I noticed some plugins like AureliumMobs or Citizens-addons, can you please try removing those plugins for a short test round to see if the problem persists? I was not able to reproduce this bug.

What addons for Citizens are you talking about?

**Comment by kangarko** [comment] 2021-12-02 17:10
Not sure, noticed CitizensText, you know better.

**Comment by NewJeb** [comment] 2021-12-06 17:02
> 

This is a common addition to the NPC text, it does not affect bosses in any way.

**Comment by kangarko** [comment] 2021-12-13 14:54
It's been almost a month, I understand the support you received was poor becaues I was unable to fix your issue, neither I believe I can, you can email me at matej@mineacademy.org to get a full refund. So sorry I was unable to resolve this, in four years we had maybe 1-2 cases like this all caused by other plugins or the server fork.
