### ISSUE TITLE
Clicking on items in boss menu, drops them.

### ISSUE THREAD

**Issue by SoraShiunin** [kangarko/Boss#256] opened 2019-02-27 11:05 UTC
On version 1.9.7.
When I click through the boss menu, the items drop on the ground. No errors in console. Items can also be picked from the menu if the menu doesn't close.
![screenshot_2067](https://user-images.githubusercontent.com/23641964/53485979-dd576900-3a87-11e9-96cc-293739549780.png)

**Comment by kangarko** [comment] 2019-02-27 12:23
I cannot reproduce. Are you sure there are no console errors from when your server loads till you execute /boss menu and click the item?

Are you able to click the item and open next menu or it just glitches?

What other plugins are you having?

**Comment by SoraShiunin** [comment] 2019-03-03 20:30
I can't find any errors on startup, while playing, when picking up the items or when closing down the server.
Yes im able to click the next menu but things like quantities item and spawn rates are very hard to change because you can pick up the item.

I have alot of plugins but I can't think of anything that would affect it. I'm not sure how to get a list, these are screenshots of the /plugins https://imgur.com/a/6HtOq0l

**Comment by kangarko** [comment] 2019-03-05 17:50
I believe it can be one of your plugin. Are you able to try temporarily whitelisting your server and only loading Boss to see if the issue persists? Also make sure to update to 2.0.x

**Comment by SoraShiunin** [comment] 2019-03-19 17:10
Found it. It was CraftEnhance.

**Comment by kangarko** [comment] 2019-03-20 18:15
Alright, I am closing this because Boss cannot fix issues in other plugins, please write to their author

**Closed by kangarko** 2019-03-20 18:15 UTC
Labels: Issue: complaint
