### ISSUE TITLE
v3.10.4 - 1.8.8: Bosses aren't recognized as such

### ISSUE THREAD

**Issue by noahmanscher** [kangarko/Boss#867] opened 2021-04-22 12:11 UTC
I've just updated to the 3.10.4 version. Players can't spawn bosses anywhere (while OP's can), but I'm sure that's just a config issue. However, when bosses are spawned, they don't show a health bar when being attacked and killing the boss (using the menu) doesn't actually kill it (and says 0 bosses in all worlds)

[Boss.zip](https://github.com/kangarko/Boss/files/6325017/Boss.zip)

**Comment by kangarko** [comment] 2021-04-29 18:11
Sorry for a late reply — Have you been experiencing this on a previous Boss version also? I cannot reproduce your issue with the health bar, check if there's any errors in the console or try only Boss and no other plugins on a local test environment to see if there's any plugin conflict.

If only OPs can spawn bosses and not players, give them these permissions:

- boss.use.spawneregg
- boss.spawn.{BOSSNAME}

replace {BOSSNAME} with your boss' name.

**Comment by kangarko** [comment] 2021-05-01 14:56
Closing in good faith this has been resolved, comment below if you still need help

**Closed by kangarko** 2021-05-01 14:56 UTC
Labels: issue

**Comment by noahmanscher** [comment] 2021-05-01 21:36
I'm sorry. Took a few days off. I haven't managed to solve this issue. The health bar thing was just an example. Bosses can't be attacked by players. Op's can hit them but not kill them. Forcefully killing them drops no loot. They act as normal iron golems, no special attacks.

**Comment by kangarko** [comment] 2021-05-02 18:11
No worries!

1. Any errors in the console?
2. Can you please only try with Boss and no other plugin installed? If not possible then you can clone this over a desktop test server.

**Comment by noahmanscher** [comment] 2021-05-03 11:23
I'll take a look. Any debug settings I should try enabling?

**Comment by noahmanscher** [comment] 2021-05-07 10:18
@kangarko ?

**Comment by kangarko** [comment] 2021-05-07 14:20
Sorry for the delay, made you a video: https://www.loom.com/share/2af8c2c18ea34af98d12f97401861881

**Comment by noahmanscher** [comment] 2021-05-07 15:23
No worries about the delay. I'll make a local test server and add plugins one by one if it works without any others.

**Comment by noahmanscher** [comment] 2021-05-07 17:32
Essentials seems to be the issue (somehow). The bosses work as intended with just a few plugins installed, but when I add essentials, the things I described start happening. I'll see if I can narrow down the issue.

**Comment by noahmanscher** [comment] 2021-05-16 13:58
@kangarko https://www.loom.com/share/8a6a31e126324600a4b0f05840e97024
Take a look at this video. I used the exact paper version you linked - still the same issues. They have the correct name and health, but no special abilities, health bars, or custom drops. I got kicked at the end of the video - seems to be an issue with the plugin sending me long messages, but that's irrelevant right now:
https://pastebin.com/xsCBxUhv

**Comment by kangarko** [comment] 2021-05-17 15:01
Looks like an issue with your client perhaps, try using a vanilla client. Also test without that SkyBlock plugin

**Comment by noahmanscher** [comment] 2021-05-17 16:25
Could be a client issue, but I doubt it, since some of my beta testers not on Lunar experienced the same issues. I'll test on vanilla. I doubt that the Skyblock plugin is an issue - I already had the issue when I tested with literally nothing but Boss, before the skyblock plugin was ever installed on my test server.

**Comment by kangarko** [comment] 2021-05-17 16:33
Please go test, and if that doesn't help then unfortunately I have no idea since it never ever happened to be reported in 4 years, apologies.

**Comment by noahmanscher** [comment] 2021-05-17 17:10
Huh. It might be an issue with the Skyblock plugin although I have no idea why - especially considering the Bosses worked with the plugin before I updated the Boss plugin. I'll investigate further.

**Comment by noahmanscher** [comment] 2021-05-20 20:31
@kangarko noticed this error while messing around with plugins:
`[WildStacker] Plugin WildStacker v3.5.2-DEVb111 has failed to register events for class com.bgsoftware.wildstacker.listeners.plugins.BossListener$NewBossListener because org/mineacademy/boss/api/event/BossSpawnEvent does not exist.`

WildStacker version `3.5.2-DEVb111` and Boss `3.10.4`. Plugin list:
`AntiDisconnectSpam, AsyncWorldEdit, AsyncWorldEditInjector, Boss, ConsoleSpamFix, DeluxeChat, EpicRename, Essentials, EssentialsChat, EssentialsSpawn, LuckPerms, Multiverse-Core, PlaceholderAPI, PlugMan, ProtocolLib, TimTheEnchanter, Vault, ViaVersion, WorldEdit`
Bosses still not working
