### ISSUE TITLE
Spawning 1.20.2 paper

### ISSUE THREAD

**Issue by josedabela** [kangarko/Boss#1243] opened 2024-04-24 12:53 UTC
I put the spawn rule to run every 900 seconds which is 15 minutes set the world limit of the boss 1 right? to only have 1 boss of that kind 1 at a time in the world.
But for example the spawn rule is set for 15 minutes but if it passes 30 minutes and a player kills that boss after the 30 minutes it spawn another right away that means the timer started when the boss spawned, not when he die.. I wanted the timer to start only when the boss die..

**Comment by kangarko** [comment] 2024-04-24 13:34
Duplicate of https://github.com/kangarko/Boss/issues/1242

**Closed by kangarko** 2024-04-24 13:34 UTC
Labels: question
